# Generated by Django 3.1.7 on 2021-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredentials',
            fields=[
                ('username', models.CharField(db_column='username', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('university', models.CharField(db_column='university', max_length=100)),
                ('auth', models.BooleanField(db_column='infoadded')),
            ],
            options={
                'db_table': 'student_credentials',
            },
        ),
        migrations.AlterField(
            model_name='facultycredentials',
            name='auth',
            field=models.BooleanField(db_column='infoadded'),
        ),
    ]
