# Generated by Django 3.2.4 on 2021-06-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_facultycredentials_auth'),
        ('grading', '0002_auto_20210621_0039'),
    ]

    operations = [
    ]
