# Generated by Django 3.1.7 on 2021-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_universities'),
    ]

    operations = [
        migrations.CreateModel(
            name='messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_column='sender', max_length=75)),
                ('reciever', models.CharField(db_column='reciever', max_length=75)),
                ('fileurl', models.CharField(db_column='fileurl', max_length=500)),
                ('dated', models.DateField(db_column='date')),
                ('time', models.TimeField(db_column='time')),
                ('status', models.BooleanField(db_column='status')),
                ('remarks', models.CharField(db_column='remarks', max_length=150)),
                ('nameStudent', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
