# Generated by Django 3.1.7 on 2021-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
